version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: petpro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_MULTIPLE_DATABASES: "petpro_auth_dev,petpro_user_dev,petpro_booking_dev,petpro_product_dev,petpro_order_dev,petpro_payment_dev,petpro_admin_dev"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-config/postgres:/docker-entrypoint-initdb.d
    networks:
      - petpro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: petpro-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - petpro-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:3.4
    container_name: petpro-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - petpro-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: petpro-kafdrop
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - kafka
    networks:
      - petpro-network

  api-gateway:
    build:
      context: ./api-gateway
      target: development
    container_name: petpro-api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CORS_ORIGIN=http://localhost:3010,http://localhost:8080
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - petpro-network
    command: npm run start:dev

  auth-service:
    build:
      context: ./auth-service
      target: development
    container_name: petpro-auth-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./auth-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - API_PREFIX=/api/v1
      - CORS_ORIGIN=http://localhost:3000,http://localhost:3010
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=petpro_auth_dev
      - JWT_SECRET=dev_jwt_secret_key_change_in_production
      - JWT_EXPIRATION=86400
      - JWT_REFRESH_SECRET=dev_jwt_refresh_secret_key_change_in_production
      - JWT_REFRESH_EXPIRATION=604800
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_GROUP_ID=auth-service-group
      - KAFKA_CLIENT_ID=auth-service
      - LOG_LEVEL=debug
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - petpro-network
    command: npm run start:dev

  admin-service:
    build:
      context: ./admin-service
      target: development
    container_name: petpro-admin-service
    restart: unless-stopped
    ports:
      - "3005:3005"
    volumes:
      - ./admin-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3005
      - API_PREFIX=/api/v1
      - CORS_ORIGIN=http://localhost:3004,http://localhost:3010
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=petpro_admin_dev
      - JWT_SECRET=admin_jwt_secret_key_change_in_production
      - JWT_EXPIRATION=86400
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_GROUP_ID=admin-service-group
      - KAFKA_CLIENT_ID=admin-service
      - LOG_LEVEL=debug
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - petpro-network
    command: npm run start:dev

  admin-gateway:
    build:
      context: ./admin-gateway
      target: development
    container_name: petpro-admin-gateway
    restart: unless-stopped
    ports:
      - "3004:3004"
    volumes:
      - ./admin-gateway:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3004
      - CORS_ORIGIN=http://localhost:3010
      - ADMIN_SERVICE_URL=http://admin-service:3005
      - AUTH_SERVICE_URL=http://auth-service:3001
      - BOOKING_SERVICE_URL=http://booking-service:3002
      - INVENTORY_SERVICE_URL=http://inventory-service:3003
      - VENDOR_SERVICE_URL=http://vendor-service:3006
      - JWT_SECRET=admin_jwt_secret_key_change_in_production
      - JWT_EXPIRATION=86400
      - LOG_LEVEL=debug
      - ADMIN_FRONTEND_URL=http://localhost:3010
    depends_on:
      - admin-service
      - postgres
      - redis
    networks:
      - petpro-network
    command: npm run start:dev

  inventory-service:
    build:
      context: ./inventory-service
      target: development
    container_name: petpro-inventory-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    volumes:
      - ./inventory-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=petpro_product_dev
      - KAFKA_BROKERS=kafka:9092
      - LOG_LEVEL=debug
    depends_on:
      - postgres
      - kafka
    networks:
      - petpro-network
    command: npm run start:dev

volumes:
  postgres-data:
  redis-data:
  kafka-data:

networks:
  petpro-network:
    driver: bridge
