#!/bin/bash
set -e

echo "===== PetPro ELK Stack Initialization ====="
echo "This script will initialize and secure the ELK Stack"

# Check if .env file exists, create if not
if [ ! -f .env ]; then
  echo "Creating .env file with default values..."
  echo "# Generated by elk-stack-init.sh - CHANGE THESE VALUES IN PRODUCTION!" > .env
  echo "ELASTIC_PASSWORD=changeme" >> .env
  echo "KIBANA_PASSWORD=changeme" >> .env
  echo "LOGSTASH_PASSWORD=changeme" >> .env
  echo "KIBANA_ENCRYPTION_KEY=at-least-32-characters-long-secure-key" >> .env
  echo "KIBANA_SMTP_PASSWORD=changeme" >> .env
  echo ".env file created with default values. Please edit with secure passwords before proceeding!"
  exit 1
else
  echo ".env file found, continuing with setup..."
fi

# 1. First, run the certificate generation
echo "Step 1: Generating certificates..."
docker compose --profile init up elasticsearch-init

# 2. Start Elasticsearch with security enabled
echo "Step 2: Starting Elasticsearch with security enabled..."
docker compose up -d elasticsearch

# Wait for Elasticsearch to be healthy
echo "Waiting for Elasticsearch to be healthy..."
attempt=1
max_attempts=10
until curl -s -u elastic:${ELASTIC_PASSWORD:-changeme} http://localhost:9200/_cluster/health | grep -q '"status":"green"'; do
  if [ $attempt -eq $max_attempts ]; then
    echo "Elasticsearch failed to become healthy after $max_attempts attempts. Check logs."
    exit 1
  fi
  echo "Attempt $attempt: Elasticsearch not ready yet, waiting..."
  sleep 10
  ((attempt++))
done
echo "Elasticsearch is healthy!"

# 3. Run the setup-users script
echo "Step 3: Setting up users and roles..."
docker compose exec elasticsearch bash -c "/usr/share/elasticsearch/setup-users.sh"

# 4. Start Logstash and Kibana
echo "Step 4: Starting Logstash and Kibana..."
docker compose up -d logstash kibana

# 5. Run Kibana initializer to import dashboards and alerts
echo "Step 5: Initializing Kibana dashboards and alerts..."
docker compose --profile init up kibana-init

echo "===== ELK Stack Initialization Complete ====="
echo "You can now access:"
echo "- Elasticsearch: http://localhost:9200 (user: elastic, password: from .env)"
echo "- Kibana: http://localhost:5601 (user: elastic, password: from .env)"
echo "- Logstash: http://localhost:9600 (metrics endpoint)"
echo ""
echo "Additional users created:"
echo "- petpro_app: Application user for backend services (password: app_password_change_me)"
echo "- petpro_dev: Developer read-only user (password: dev_password_change_me)"
echo ""
echo "Important: Change all default passwords before using in production!"
