export enum ActivityType {
  LOGIN = 'login',
  LOGOUT = 'logout',
  PROFILE_UPDATE = 'profile_update',
  PASSWORD_CHANGED = 'password_changed',
  EMAIL_VERIFIED = 'email_verified',
  BOOKING_CREATED = 'booking_created',
  BOOKING_UPDATED = 'booking_updated',
  BOOKING_CANCELLED = 'booking_cancelled',
  PAYMENT_MADE = 'payment_made',
  PAYMENT_REFUNDED = 'payment_refunded',
  PET_CREATED = 'pet_created',
  PET_UPDATED = 'pet_updated',
  PET_REMOVED = 'pet_removed',
  REVIEW_SUBMITTED = 'review_submitted',
  ADDRESS_ADDED = 'address_added',
  ADDRESS_UPDATED = 'address_updated',
  ADDRESS_REMOVED = 'address_removed',
  NOTIFICATION_SETTINGS_UPDATED = 'notification_settings_updated',
  ACCOUNT_CREATED = 'account_created',
  ACCOUNT_DEACTIVATED = 'account_deactivated',
  ACCOUNT_REACTIVATED = 'account_reactivated',
}
