name: Web Admin CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'web-admin/**'
      - '.github/workflows/web-admin-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'web-admin/**'
      - '.github/workflows/web-admin-ci.yml'

jobs:
  # Run quality checks for the web admin code
  quality:
    name: Web Admin Quality Checks
    uses: ./.github/workflows/quality-checks.yml
    with:
      working-directory: ./web-admin
      node-version: '18'
      eslint: true
      prettier: true
      typescript: true
      sonarqube: false
    secrets: inherit

  # Build and test the web admin portal
  build-and-test:
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: web-admin/package-lock.json

      - name: Install dependencies
        working-directory: ./web-admin
        run: npm ci

      - name: Run tests
        working-directory: ./web-admin
        run: npm test -- --coverage

      - name: Build
        working-directory: ./web-admin
        run: npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-admin-build
          path: web-admin/build
          retention-days: 1

  # Handle test coverage separately
  coverage:
    name: Web Admin Test Coverage
    needs: build-and-test
    uses: ./.github/workflows/test-coverage.yml
    with:
      working-directory: ./web-admin
      coverage-directory: coverage
      flags: web-admin
      name: web-admin-coverage
      min-coverage: 70
      test-command: npm test -- --coverage
    secrets: inherit
